modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
[[mods]]
modId="tiny_coals"
version="${file.jarVersion}"
displayName="Tiny Coals"
credits="Thank you."
authors="Love,goulixiaoji of Abstruck"
description='''
I brought back the Tiny Coals to 1.18.2!
'''

[[dependencies.tiny_coals]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tiny_coals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
